# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 29 Dec 2013 13:15:26 +0000
*	@ALL	1
*	@user	1
*	@writer	2
*	@uploader	8
*	@creater	4
